[package]
name = "quad-androidx"
version = "0.1.0"
edition = "2021"
license = "MIT/Apache-2.0"
description = "Access to androidx.core.* for miniquad's java"
readme="README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
