comptime_jar_files = [ 
    "java/core-1.8.0.jar",
    "java/annotation-1.3.0.jar",
    "java/collection-1.2.0.jar",
    "java/concurrent-futures-1.1.0.jar"
]
runtime_jar_files = [
    "java/core-1.8.0.jar",
    "java/collection-1.2.0.jar",
    "java/concurrent-futures-1.1.0.jar"
]
